### ISSUE TITLE
Introduce proper k8s resources (CPU and Memory)

### ISSUE THREAD

**Issue by amroakmal** [m3ntorship/backend-nestjs-template#25]
### Story
Introduces memory and CPU requests/limits

### Tasks
- [ ] CPU and memory declared as following 

```yaml
resources:
  limits:
    memory: "300"
  requests:
    cpu: "100"
	memory: "300" 
```
